[tool.semantic_release]
version_variables = [
    "src/version.py:__version__",
]
build_command = "echo 'No build required'"
major_on_zero = true
branch = "master"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.remote.token]
env = "GITHUB_TOKEN"

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"

[tool.semantic_release.branches.master]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false
