name: Continuous Delivery

on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read

jobs:
  bump-version:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false

    permissions:
      contents: write

    outputs:
      new_version: ${{ steps.set-new-version.outputs.new_version }}
      released: ${{ steps.release.outputs.released }}

    steps:
      - name: Setup | Checkout Repository on Release Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup | Force release branch to be at workflow sha
        run: |
          git reset --hard ${{ github.sha }}

      - name: Evaluate | Verify upstream has NOT changed
        shell: bash
        run: |
          set +o pipefail

          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
          printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"

          set -o pipefail

          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
              printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
              exit 1
          fi

          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"

          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
              printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
              exit 1
          fi

          HEAD_SHA="$(git rev-parse HEAD)"

          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
              printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
              printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
              exit 1
          fi

          printf '%s\n' "Verified upstream branch has not changed, continuing with release..."

      - name: Action | Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      - name: Set new_version output
        id: set-new-version
        run: |
          echo "Released version: ${{ steps.release.outputs.released }}"
          echo "New version: ${{ steps.release.outputs.version }}"
          echo "new_version=${{ steps.release.outputs.version }}" >> $GITHUB_OUTPUT

  build-windows:
    runs-on: windows-latest
    needs: bump-version
    if: needs.bump-version.outputs.released == 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows executable
        run: |
          cd scripts
          python build_exe.py ${{ needs.bump-version.outputs.new_version }}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: scripts/dist/AdvancedAutoClicker_v${{ needs.bump-version.outputs.new_version }}.exe

  build-linux:
    runs-on: ubuntu-latest
    needs: bump-version
    if: needs.bump-version.outputs.released == 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Linux executable
        run: |
          cd scripts
          chmod +x build_linux.sh
          ./build_linux.sh ${{ needs.bump-version.outputs.new_version }}

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-executable
          path: scripts/dist/AdvancedAutoClicker_v${{ needs.bump-version.outputs.new_version }}

  create-release:
    runs-on: ubuntu-latest
    needs: [bump-version, build-windows, build-linux]
    if: needs.bump-version.outputs.released == 'true'
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-executable
          path: ./artifacts/windows/

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-executable
          path: ./artifacts/linux/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.bump-version.outputs.new_version }}
          name: Release v${{ needs.bump-version.outputs.new_version }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/windows/AdvancedAutoClicker_v${{ needs.bump-version.outputs.new_version }}.exe
            ./artifacts/linux/AdvancedAutoClicker_v${{ needs.bump-version.outputs.new_version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  
