name: Release Advanced Auto Clicker

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    name: Determine next version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semantic_release.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Calculate next semantic version
        id: semantic_release
        uses: gitversion/semantic-release-action@v3
        with:
          dry_run: false
          build_metadata: false

  build-linux:
    needs: bump-version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.bump-version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter pyautogui pynput pillow keyboard

      - name: Build Linux executable
        run: |
          chmod +x ./build-linux.sh
          ./build-linux.sh "$VERSION"

      - name: Upload Linux executable
        uses: actions/upload-artifact@v3
        with:
          name: AdvancedAutoClicker-linux-$VERSION
          path: ./dist/AdvancedAutoClicker

  build-windows:
    needs: bump-version
    runs-on: windows-latest
    env:
      VERSION: ${{ needs.bump-version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter pyautogui pynput pillow keyboard

      - name: Build Windows executable
        run: |
          call .\install_deps.bat
          python build_exe.py %VERSION%

      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: AdvancedAutoClicker-windows-${{ env.VERSION }}
          path: .\dist\AdvancedAutoClicker.exe

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.bump-version.outputs.new_version }}
          name: Advanced Auto Clicker ${{ needs.bump-version.outputs.new_version }}
          body: |
            Automated release generated by GitHub Actions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux executable to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.bump-version.outputs.new_version }}
          name: AdvancedAutoClicker-linux-${{ needs.bump-version.outputs.new_version }}
          asset_path: ./dist/AdvancedAutoClicker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows executable to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.bump-version.outputs.new_version }}
          name: AdvancedAutoClicker-windows-${{ needs.bump-version.outputs.new_version }}.exe
          asset_path: .\dist\AdvancedAutoClicker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
